[project]
name = "clizot"
version = "0.1.0"
description = "A CLI tool to interface with Zotero installations"
requires-python = ">=3.8"
dependencies = [
    "pytest>=8.3.5",
]

[project.scripts]
clizot = "cli:main"

[tool.uv]
dev-dependencies = [
    "pytest>=6.0",
]
